
WITH T AS (
    SELECT BOOK_ID, CATEGORY, PRICE, B.AUTHOR_ID, A.AUTHOR_NAME
    FROM BOOK B JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
)

SELECT T.AUTHOR_ID, T.AUTHOR_NAME, CATEGORY, SUM(SALES * T.PRICE) AS TOTAL_SALES
FROM T JOIN BOOK_SALES BS ON T.BOOK_ID = BS.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC
