WITH T AS (
    SELECT I1.ITEM_ID AS ITEM_ID, I2.PARENT_ITEM_ID AS PARENT_ID
    FROM ITEM_TREE I1 LEFT JOIN ITEM_TREE I2 ON I1.ITEM_ID = I2.PARENT_ITEM_ID
)

SELECT II.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO II JOIN T ON II.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ID IS NULL
ORDER BY II.ITEM_ID DESC