-- 코드를 작성해주세요
SELECT ID,
       CASE
           WHEN PRANK <= 0.25 THEN 'CRITICAL'
           WHEN PRANK <= 0.5 THEN 'HIGH'
           WHEN PRANK <= 0.75 THEN 'MEDIUM'
           ELSE 'LOW'
       END AS COLONY_NAME
FROM (
    SELECT ID,
           SIZE_OF_COLONY,
           PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PRANK
    FROM ECOLI_DATA
) AS RANKED
ORDER BY ID
