SELECT YEAR(SALES_DATE) AS YAER, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT U.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT U.USER_ID)/ (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO
FROM USER_INFO U JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE U.JOINED LIKE '2021%'
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)