WITH TEMP AS (
    SELECT HISTORY_ID, CAR_TYPE, DAILY_FEE, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION,
            CASE 
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
                ELSE 'NONE'
            END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS T1 JOIN CAR_RENTAL_COMPANY_CAR AS T2 ON T1.CAR_ID = T2.CAR_ID
    WHERE CAR_TYPE = '트럭'
)

SELECT HISTORY_ID, 
    ROUND((DAILY_FEE * DURATION) * (100 - IFNULL(C.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM TEMP AS T LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON T.CAR_TYPE = C.CAR_TYPE AND T.DURATION_TYPE = C.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC