WITH CS220413 AS (
    SELECT AP.APNT_YMD, APNT_NO, AP.MCDP_CD, DR_NAME, PT_NO
    FROM APPOINTMENT AS AP INNER JOIN DOCTOR AS D ON AP.MDDR_ID = D.DR_ID
    WHERE DATE(AP.APNT_YMD) = '2022-04-13' AND AP.MCDP_CD = 'CS' AND APNT_CNCL_YN = 'N'
)
SELECT APNT_NO, P.PT_NAME, D.PT_NO, D.MCDP_CD, DR_NAME, D.APNT_YMD
FROM CS220413 AS D JOIN PATIENT AS P ON D.PT_NO = P.PT_NO
ORDER BY APNT_YMD
