-- 코드를 작성해주세요
WITH TEMP AS (
    SELECT II.ITEM_ID, ITEM_NAME, RARITY, PARENT_ITEM_ID
    FROM ITEM_INFO II INNER JOIN ITEM_TREE IT ON II.ITEM_ID = IT.ITEM_ID
)

SELECT T.ITEM_ID, T.ITEM_NAME, T.RARITY
FROM TEMP T
WHERE T.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY ITEM_ID DESC

