-- 코드를 입력하세요
WITH TEMP AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) = 10)
    
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR as crcc
where crcc.CAR_TYPE = '세단' AND crcc.CAR_ID IN (SELECT * FROM TEMP)
ORDER BY CAR_ID DESC